### ISSUE TITLE
Paypal Module

### ISSUE THREAD

**Issue by twitnic** [EU-Legal/modules-1.6.0.11#1]
Hey,

Ich habe heute das Modul mal von .o.9 auf diese .0.11 Version aktualisert.

Aktuell haben wir den Shop noch nicht freigeschalten, daher habe ich - um alle Fehler zu finden - den Dev-Modus an. Da ist mir beim bezahlen am Ende bei der Auswahl der Zahlungsart folgendes aufgefallen:

Notice: Undefined index: module in /www/htdocs/xxxxxxx/remidemmi.de/modules/paypal/paypal.php on line 711

Vielleicht kann man das ja noch fixen ....

Danke für die tolle Arbeit.

**Comment by jBangiev** [comment]
Hallo,

das ist ein Bug von PayPal Modul und nicht von EU Legal. Dieser erscheint bei den eingeschalteten Fehlermeldungen auch ohne EU Legal und soll von PayPal-Modul Entwickler gelöst werden.
