### ISSUE TITLE
Preisdarstellung: "Ab" falsch im Template

### ISSUE THREAD

**Issue by twitnic** [EU-Legal/modules-1.6.0.11#10]
Hallo,

habe das aktuelle EU Legal installiert, aber das "ab" vor dem Preis ist jetzt dahinter?!?
Kennt jemand eine Lösung für das Problem?
http://remidemmi.de/nice-to-have/55-hundekissen-vintage.html

Danke euch

**Comment by jBangiev** [comment]
Das Problem haben wir vorher schon gelöst? Ist das die aktuelle Dev-Version https://github.com/EU-Legal/modules-1.6.0.11/tree/dev?

**Comment by twitnic** [comment]
Sollte die aktuelle stabile Version sein. Dachte ich ...
Mal die aus dem Dev-Branch drüber kopieren? Oder reicht das nicht?

**Comment by jBangiev** [comment]
Das reicht nicht, bitte reinstallieren.

**Comment by twitnic** [comment]
Jop, hat funktioniert. Vielen Dank.
Danke für eure Arbeit
