### ISSUE TITLE
EU Legal kann nicht in Presta Cloud Shop installiert werden, Fehlermeldung: Fail to extract module zip file

### ISSUE THREAD

**Issue by frauchenvonlassie** [EU-Legal/modules-1.6.0.11#15]
Hallo,
wie von Ihnen beschrieben, habe ich das Prestashop Addons Portal geöffnet, das neueste EU Legal Modul ausgewählt und den Download-Button geklickt. Dann hat sich ein Popup geöffnet, das die Installation in meinem Shop anbietet. Ich habe dieses angeklickt und es kam folgende Fehlermeldung: Fail to extract module zip file
Ich habe das Prozedere mehrmals versucht, auch an verschiedenen Tagen, immer mit der gleichen Fehlermeldung: Fail to extract module zip file (andere kostenlose Module, wie z.B. Sofortüberweisung oder Trusted Shops konnte ich dagegen problemlos installieren).
Können Sie mir bitte weiterhelfen, da ich den Shop nicht eröffnen und rechtssicher betreiben kann. Sicher bin ich nicht die Einzige mit dieser Fehlermeldung bei der Installation im Cloud Shop.
Vielen Dank!
Cristina

**Comment by JonasEriksson** [comment]
Hallo Cristina, ich bin kein Prestashop Profi, stand aber vor einem ähnlichen Problem, ich finde mich heute zumindest weiter vorangeschritten als gestern...

Schritt 1 ist auf jeden Fall das Anlegen eines FTP Users im Prestahop Shop Account (also NICHT im prestahop Backend/Adminbereich, sondern in dem Cloud Adminbereich). Damit kann man dann die Inhalte des heruntergeladenen und entpackten ZIP Files aus dem Add-On Shop in das Verzeichnis MODULES im Hauptverzeichnis nach dem FTP Login hochladen.

Schritt 2 ist dann das "Installieren" des EU Legal Moduls im Prestadhop Adminbereich unter Module. Das taucht dort nun nämlich auf. Wenn nicht, einfach nochmal den Cache in Prestahop-Admin ("Voreinstellungen" -> "Leistung") löschen und am besten auch im Browser. EU Legal sollte dort unter Module auffindbar sein, einfach mal nach "legal" suchen.

Wenn nun eine Fehlermedlung a la "[PrestaShop] Fatal error in module file :/home/pfr5162220/www/ftp/modules/eu_legal/eu_legal.php:
Uncaught exception 'ReflectionException' with message 'Class OrderOverrideOriginal54dc8e4e9f1e7 does not exist' in /home/pfr5162220/www/ftp/modules/eu_legal/eu_lega......" kommt, liegt es scheibar an den "Overrides". Da mir zunächst auch nicht klar war, welche overrides wo ein Problem darstellen, zog ich das Override Verzeichnis per FTP auf meinen Rechner als Backup, und löschte dann alle Sachen aus dem Verzeichnis raus, wobei die Unterverzeichnisse drin bleiben. 

Damit liess sich dann EU Legal installieren.


Wie gesagt - OHNE JEDE GEWÄHR - ich bin kein Prestashop-Profi und arbeite an einem Cloudsystem, welches nicht produktiv im Einsatz ist. 

Vielleicht hilft es aber etwas weiter!

**Comment by frauchenvonlassie** [comment]
Hallo Jonas,
ich nutze keine Downloadversion von Prestashop, sondern die vollständig gehostete PrestaShop-Cloud (seit kurzem kostenlos online). Dort kann leider kein FTP User angelegt werden. Man ist darauf angewiesen, dass die Installation ausschließlich über das Prestashop Addons Portal fehlerfrei funktioniert. Es gibt keine andere Möglichkeit, ein Modul von Hand zu installieren oder zu konfigurieren. Die Fehlermeldung "Fail to extract module zip file" bei dem Modul EU Legal kann also nur von den Entwicklern selbst behoben werden. Nur das Modul EU Legal ist daher nicht in der vollständig gehostete PrestaShop-Cloud installierbar, andere Module konnte ich problemlos über das Addon Portal für die gehostete Cloud Version installieren.
Vielleicht kann mir jemand von den Entwicklern Bescheid geben, wann das Modul EU Legal für die gehostete Cloudversion von Prestashop über das Prestashop Addons Portal installiert werden kann, damit ich meinen Shop endlich eröffnen und rechtssicher betreiben kann.
Danke!
Cristina

**Comment by JonasEriksson** [comment]
Hallo Cristina,
ich schrieb ja auch, dass ich die Cloudversion nutze. Es scheint ein "weit verbreitetes" Missverständnis zu sein, dass man als Prestashop Cloud User keinen FTP Account anlegen kann. Du musst mir jetzt einfach glauben, dass das doch geht, und hier ist ein Screenshot, wo man das findet bzw. anlegt. Danach kommst du wunderbar via FTP auf deinen Cloudbereich. :-)  Viele Grüße, Jonas

![prestashop-cloud-ftp-user-anlegen](https://cloud.githubusercontent.com/assets/701938/6172372/a5e51c84-b2e0-11e4-9b2d-d0221e6708fe.jpg)

**Comment by frauchenvonlassie** [comment]
Hallo Jonas,
super, hat jetzt dank deiner ausführlichen Anleitung geklappt, ich konnte die Datei als entzippte Version via ftp in das Verzeichnis Module hochladen und installieren :-)
Danke nochmal und einen schönen Abend!
Cristina

**Comment by JonasEriksson** [comment]
Super, dass es geklappt hat! Übrigens: Falls du den "issue" hier schliessen kannst, wissen die Entwickler, dass dieser Punkt soweit abgeschlossen ist. (Ich glaube zumindest, dass ich das nicht machen kann) LG, Jonas

**Comment by frauchenvonlassie** [comment]
Alles klar, ist hiermit geschlossen ;-)

**Comment by jBangiev** [comment]
Vielen Dank für diese Mitteilung. Wir nehmen mit Addons den Kontakt auf und schildern das Problem. Denn wir haben leider keinen direkten Einfluss auf die Installationsroutine im Cloud.
