### ISSUE TITLE
Übersicht Warenkorb - Entfernen und Gesamt vertauscht

### ISSUE THREAD

**Issue by jigsawIV** [EU-Legal/modules-1.6.0.11#19]
Ist auch im Demo-Shop von Silbersaiten.

![bildschirmfoto 2015-02-20 um 16 24 21](https://cloud.githubusercontent.com/assets/5776577/6288950/0f8a3614-b91d-11e4-8042-8ef1d9f330b8.png)

**Comment by gurkcity** [comment]
Fixed in dev> https://github.com/EU-Legal/modules-1.6.0.11/commit/eb7a098005beca1546fc103a303c184686f4e061
