### ISSUE TITLE
Versandkostenfehler

### ISSUE THREAD

**Issue by kalua7** [EU-Legal/modules-1.6.0.11#23]
Hallo

Ich habe ein seltsames Problem das leider definitv mit EU Legal zusammenhängt.
Im Detail geht es darum das im Warenkorb Versandkosten angezeigt werden, die durch eine Warenkorbregel deaktivert sein sollten. Hier Step bei Step.

1. Hier ist noch alle korrekt. Der Warenkorb ist unter 50,- inkl. Mwst und der Versand wird angezeigt.
![versand1](https://cloud.githubusercontent.com/assets/10958606/7005843/55969e0e-dc7c-11e4-846f-6d99b3ec5a07.JPG)

2. Hier habe ich die Stückzahl um 1 erhöht. Wie man sieht werden die Versandkosten zwar nicht berechnet, jedoch angezeigt.
![versand2](https://cloud.githubusercontent.com/assets/10958606/7005844/5597c64e-dc7c-11e4-9211-654faca03f06.JPG)

3. Hier habe ich nochmals die Stückzahl um 1 erhöht und plötzlich ist alles richtig. Gesamtsumme und der Hinweis auf die Versandkosten ist weg.
![versand3](https://cloud.githubusercontent.com/assets/10958606/7005845/55983732-dc7c-11e4-9959-4b22d338df8b.JPG)

4. Und jetzt wird es spannend. Ich habe die Stückzahl um 1 reduziert. Also der identische Wert wie im 2. Screenshot von oben mit 6 Artikeln im Warenkorb. Jetzt jedoch ist die Berechnung richtig und auch die Versandkosten erscheinen nicht.
![versand4](https://cloud.githubusercontent.com/assets/10958606/7005842/559577cc-dc7c-11e4-9a10-cdad4b66b986.JPG)

Testweise habe ich das EU Modul deaktiviert und mit deaktiviertem EU-Modul werden alle Daten korrekt angezeigt.

Bitte um Info wo, was zu tun ist/wäre

**Comment by kalua7** [comment]
Wäre schön wenn da mal jemand antworten könnte

**Comment by gurkcity** [comment]
Dies ist kein Problem von EU Legal. Dieser Bug tritt auch im PrestaShop original auf.
=> angemeldeter Kunde (Versandadresse ist vorhanden)
=> Versanddienstleister noch nicht gewählt
Erst wenn eine von beiden Bedingungen gesetzt ist, dann greift das JavaScript, welches zur Anzeige und Wechsel des kostenlosen Versandes zuständig ist.

**Comment by kalua7** [comment]
Hey Chris

Ich weiss nicht was ihr getestet habt, aber ich habe gerade EU deinstalliert und der Fehler war weg.

Screenshot 1 zeigt den Warenkorb kurz unter 50,- Euro
![fehlerohneumodul1](https://cloud.githubusercontent.com/assets/10958606/7255357/034cbc4a-e849-11e4-91a7-87af110a7f3b.JPG)

Dann habe ich das Produkt um eins erhöht ..
![fehlerohneumodul2](https://cloud.githubusercontent.com/assets/10958606/7255354/0347d270-e849-11e4-9e5a-85087f35d99e.JPG)
und die Versandkosten werden ausgeblendet.

exakt das selbe Beispiel mit installiertem EU Modul ...
![fehlerohneumodul3](https://cloud.githubusercontent.com/assets/10958606/7255355/034a1922-e849-11e4-84a7-767a55dce5bf.JPG)

um eines erhöht ...
![fehlerohneumodul4](https://cloud.githubusercontent.com/assets/10958606/7255356/034adda8-e849-11e4-94d3-cc45b9c965c0.JPG)

**Comment by gurkcity** [comment]
Diskussion geht hier weiter:
https://www.prestashop.com/forums/topic/434982-versandkostenfrei-wird-berechnet-aber-nicht-angezeigt/
