### ISSUE TITLE
inkl MwSt

### ISSUE THREAD

**Issue by RXBeat** [EU-Legal/modules-1.6.0.11#3]
Ich weiß nicht ob das wirklich ein Fehler ist aber wenn ich Grundpreise eingebe dann sieht es so aus...
Grundpreis: 64,14 € pro 1 kg
Bin mir jetzt nicht sicher, muss es nicht heißen:
Grundpreis: 64,14 € inkl. MwSt. pro 1 kg 
oder sogar vielleicht
Grundpreis: 64,14 € inkl. 7% MwSt pro 1 kg 
Ich dachte das ist auch gesetzlich vorgegeben. Ein mal checken please :)

**Comment by Nobodaddy** [comment]
Quälgeist ! ;-)
I proposed this change:
https://github.com/EU-Legal/modules-1.6.0.11/pull/4

**Comment by Magicalname** [comment]
der Prozentsatz ist ein kann, kein muss!

**Comment by Nobodaddy** [comment]
Sobald das Online-Angebot prinzipiell auch Käufern aus anderen europäischen Ländern zur Verfügung stehen soll, darf hier gar kein Prozentsatz stehen, es sei denn der des jeweiligen Landes, aus dem der Käufer stammt. Das kennt der Shop aber erst, wenn sich der Käufer angemeldet hat!

**Comment by jBangiev** [comment]
inkl. MwSt. muss hier auch nicht stehen, denn diese Angabe bezieht sich auf die Angabe des Verkaufspreises.

**Comment by Nobodaddy** [comment]
Hallo Julia,
das Problem ist nur, dass man die Preisangabenverordnung durchaus auch anders verstehen kann:

"Wer Letztverbrauchern gewerbs- oder geschäftsmäßig oder regelmäßig in sonstiger Weise Waren in Fertigpackungen, offenen Packungen oder als Verkaufseinheiten ohne Umhüllung nach Gewicht, Volumen, Länge oder Fläche anbietet, hat neben dem Gesamtpreis auch den Preis je Mengeneinheit einschließlich der Umsatzsteuer und sonstiger Preisbestandteile (Grundpreis) in unmittelbarer Nähe des Gesamtpreises gemäß Absatz 3 Satz 1, 2, 4 oder 5 anzugeben." (§ 2 Abs. 1 PAngV)

Es gilt zwar seit dem 12. Juni 2013, dass gewerbliche Verkäufer bei Angeboten von Waren gegenüber Verbrauchern  nicht mehr angeben müssen, dass die angegebenen Preise die Umsatzsteuer und sonstige Preisbestandteile enthalten, aber nur, wenn Sie ihre Waren nicht online verkaufen, da § 1 Absatz 2 Satz 1 Nr. 1 PAngV im nicht-online Fernabsatzhandel keine Anwendung mehr findet. 

Dagegen gilt  für Preisangaben im Online-Geschäft (also etwa für Webshops) § 1 Absatz 2 Satz 1 Nr. 1 PAngV unverändert fort, d. h. gewerbliche Verkäufer müssen bei Warenangeboten von Waren gegenüber Verbrauchern weiterhin bei ALLEN Preisen angeben, dass diese die Umsatzsteuer und sonstige Preisbestandteile enthalten.

Der Händlerbund hält zwar eine Grundpreisangabe ohne expliziten MwSt-Ausweis für rechtlich unbedenklich. Das mag, wenn es zum Gerichtsverfahren kommt, letztlich auch sein - aber ob das auch die Abmahnhaie so sehen?
Es schadet also nichts, sicherheitshalber auch hier die enthaltene MwSt. kenntlich zu machen.
